apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: kanban-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kanban-nginx
  template:
    metadata:
      labels:
        app: kanban-nginx
    spec:
      containers:
      - name: kanban-nginx-app
        image: 27678/dockerbootcamp1:v1
        ports:
        - containerPort: 80
