apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    services.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  # type: NodePort
  selector:
    app: kanban-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: 30301
  type: LoadBalancer
